import re

test = """
      'KSC Lokeren Oost-Vlaanderen',
      'Juventus FC',
      'FC Nantes',
      'SSC Napoli',
      'Cercle Brugge KSV',
      'Royal Antwerp FC',
      'SS Lazio',
      'Olympique de Marseille',
      'YR KV Mechelen',
      'Club Brugge KV',
      'SL Benfica',
      'Waasland-Beveren',
      'Sint-Truidense VV',
      'PFC CSKA',
      'KV Oostende',
      'KRC Genk',
      'FC Schalke 04',
      'KAA Gent',
      'FC Porto',
      'Royal Excel Mouscron',
      'Bayer 04 Leverkusen',
      'Royal Standard de Liège',
      'FC Shakhtar Donetsk',
      'AS Saint-Étienne',
      'FC Lokomotiv Moscow',
      'RSC Anderlecht',
      'Olympique Lyonnais',
      'Real Betis Balompié',
      'Oud-Heverlee Leuven',
      'Sporting du Pays de Charleroi',
      'AS Roma',
      'FK Spartak Moskva',
      'Gimnasia y Esgrima La Plata',
      'SV Zulte-Waregem',
      'KAS Eupen',
      'KV Kortrijk',
      'West Ham United FC',
      'Club Atlético de Madrid',
      'Lille OSC Métropole',
      'Valencia CF',
      'FK Dinamo Moskva',
      'Sporting Clube de Portugal',
      'KFCO Beerschot-Wilrijk',
      'Urawa Red Diamonds',
      'Ulsan Hyundai Horang-i',
      'Incheon United FC',
      'Real Salt Lake',
      'Kawasaki Frontale',
      'Sanfrecce Hiroshima',
      'Gamba Osaka',
      'FC Tokyo',
      'Colorado Rapids',
      'Suwon Samsung Bluewings FC',
      'Portland Timbers',
      'FC Dallas',
      'Philadelphia Union',
      'Consadole Sapporo',
      'Kashiwa Reysol',
      'Pohang Steelers FC',
      'New York Red Bulls',
      'Shimizu S-Pulse',
      'Daegu FC',
      'New York City FC',
      'Shonan Bellmare',
      'Kashima Antlers',
      'Yokohama F. Marinos',
      'Gwangju FC',
      'Toronto FC',
      'Vegalta Sendai',
      'Busan I Park',
      'D.C. United',
      'Vissel Kobe',
      'Sagan Tosu',
      'Los Angeles FC',
      'New England Revolution',
      'Jeonbuk Hyundai Motors FC',
      'Cerezo Osaka',
      'Seongnam FC',
      'San Jose Earthquakes',
      'Chicago Fire FC',
      'Orlando City SC',
      'Seattle Sounders FC',
      'Yokohama FC',
      'Inter Miami CF',
      'FC Seoul',
      'Gangwon FC',
      'Oita Trinita',
      'Vancouver Whitecaps FC',
      'Columbus Crew SC',
      'Nagoya Grampus',
      'Nashville SC',
      'Sangju Sangmu Phoenix FC',
      'Sporting Kansas City',
      'Atlanta United FC',
      'Montreal Impact',
      'Minnesota United FC',
      'FC Cincinnati',
      'Houston Dynamo',
      'Paris Saint-Germain FC',
      'FK Zenit St. Petersburg',
      'FC Bayern München',
      'FC Arouca',
      'FK AS Trenčín',
      'Fortuna Sittard',
      'FC Famalicão',
      'Club Atlético Nacional SA',
      'VfL Wolfsburg',
      'ACF Fiorentina',
      'FC Basel 1893',
"""

price1 = re.sub(r"'", '', test)
price2 = re.sub(r',', '', price1)
price4 = re.sub(r' ', '', price2)
price3 = price4.split('\n')
price3.pop(0)
price3.pop(-1)

for i in price3:
    print(i + ' = auto()')
